# Generated by Django 3.0.3 on 2020-02-19 13:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_photos/'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_created=True)),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('captions', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('caption_style', models.CharField(max_length=100)),
                ('aspect_ratio', models.CharField(max_length=100)),
                ('caption_position_v', models.IntegerField()),
                ('caption_position_h', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center')], max_length=1)),
                ('headline', models.CharField(max_length=100)),
                ('headline_style', models.CharField(max_length=100)),
                ('headline_position_h', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center')], max_length=1)),
                ('headline_position_v', models.IntegerField()),
                ('zoom', models.IntegerField()),
                ('background_color', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
