# Generated by Django 3.0.3 on 2020-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200220_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='language_code',
            field=models.CharField(default='en_us', max_length=20),
        ),
    ]
