# Generated by Django 3.0.3 on 2020-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_video_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='result_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='aspect_ratio',
            field=models.CharField(choices=[('widescreen', '16:9 Widescreen'), ('square', '1:1 Square'), ('portrait', '4:5 Portrait'), ('vertical', '9:16 Vertical')], default='widescreen', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='background_color',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_style',
            field=models.CharField(choices=[('standart_captions', 'Standart captions'), ('minimal_captions', 'Minimal captions')], default='standart_captions', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='headline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='headline_style',
            field=models.CharField(choices=[('standart_headline', 'Standart headline'), ('minimal_headline', 'Minimal headline')], default='standart_headline', max_length=100),
        ),
    ]
