# Generated by Django 3.0.3 on 2020-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200306_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='on_process',
            field=models.BooleanField(default=False),
        ),
    ]
